* Seamstress
Seamstress is an art engine.
The goal is to provide a [[https://lua.org][Lua]] environment for users to create
sequencers, music, games, visuals, etc.
It is inspired by [[https://monome.org/docs/norns][norns]], [[https://love2d.org][Love2D]], [[https://hydra.ojack.xyz][Hydra]] and [[https://nodejs.org][Node.js]].
Seamstress version 2 is *alpha* software.

* Usage

Currently Seamstress is a very bare-bones command-line program.
You can load a Lua file by running `seamstress FILENAME`,
or execute Lua code from the REPL prompt.

* Installation

I provide release builds of Seamstress here on GitHub.
At the moment, Seamstress has very little in terms of external dependencies,
so I'm optimistic that these are useful artifacts.
Please let me know if you encounter issues with using them.

* Contributing

If you're excited by the Seamstress project, I'd love to collaborate!
Please reach out.

* Building from source

To build from source, you’ll need the [[https://ziglang.org][Zig]] compiler.
Seamstress will always track releases of the Zig compiler,
so be sure to grab the latest release, rather than the master build.
To compile Seamstress, clone this repository
and run =zig build= in the repository root.
(NB: you’ll need an internet connection so that the Zig compiler can fetch dependencies.)

Doing so will place the compiled executable in =./zig-out/bin=.
You can add this folder to your =$PATH= to make =seamstress= available from your shell,
symlink it somewhere on your =$PATH=,
or copy the files installed into =zig-out= somewhere in your =$PATH=.

I develop Seamstress primarily on macOS.
It is a design goal for Seamstress to be cross-platform,
but I may not always be able to focus much effort towards this on my own;
If you're able to help in this, I'd be very grateful for your support.
