name: test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - name: check out Lua
        if: startsWith(matrix.os, 'windows') != true
        uses: actions/checkout@v4
        with:
          repository: robbielyman/lua
          path: .lua
      - name: compile Lua
        if: startsWith(matrix.os, 'windows') != true
        run: cd .lua && zig build -Dshared=true --prefix .
      - uses: ilammy/msvc-dev-cmd@v1
      - name: set up Lua (windows)
        if: startsWith(matrix.os, 'windows')
        uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.4.7"
      - uses: luarocks/gh-actions-luarocks@v5
      - run: luarocks install busted
      - run: zig build test
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: 0.13.0
      - run: zig fmt --check .
