name: test
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - uses: ilammy/msvc-dev-cmd@v1
      - uses: leafo/gh-actions-lua@v11
        with:
          luaVersion: "5.4.7"
      - uses: luarocks/gh-actions-luarocks@v5
      - run: luarocks install busted
      - run: zig build
      - run: zig build test
        timeout-minutes: 5
        continue-on-error: true
      - run: zig build run -- --test
        timeout-minutes: 1
        continue-on-error: true
  check-fmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check .
